// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'b19d7fe4c5aedf14796ab92b52b24a865677096f91d953bd8a6ba020f374c514'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type OrderItemOutput = {
  readonly ticketCategoryId: CodecTypes['mongo/objectId@1']['output'];
  readonly quantity: CodecTypes['mongo/int32@1']['output'];
};
export type OrderItemInput = {
  readonly ticketCategoryId: CodecTypes['mongo/objectId@1']['input'];
  readonly quantity: CodecTypes['mongo/int32@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly EventSettings: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly date: CodecTypes['mongo/string@1']['output'];
      readonly location: CodecTypes['mongo/string@1']['output'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly buyerName: CodecTypes['mongo/string@1']['output'];
      readonly buyerPhone: CodecTypes['mongo/string@1']['output'];
      readonly buyerEmail: CodecTypes['mongo/string@1']['output'] | null;
      readonly items: ReadonlyArray<OrderItemOutput>;
      readonly totalAmount: CodecTypes['mongo/int32@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Payment: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly orderId: CodecTypes['mongo/objectId@1']['output'];
      readonly method: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly waveReference: CodecTypes['mongo/string@1']['output'] | null;
      readonly confirmedByUserId: CodecTypes['mongo/objectId@1']['output'] | null;
      readonly confirmedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Ticket: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly orderId: CodecTypes['mongo/objectId@1']['output'];
      readonly ticketCategoryId: CodecTypes['mongo/objectId@1']['output'];
      readonly code: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly usedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly scannedByUserId: CodecTypes['mongo/objectId@1']['output'] | null;
    };
    readonly TicketCategory: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly price: CodecTypes['mongo/int32@1']['output'];
      readonly currency: CodecTypes['mongo/string@1']['output'];
      readonly stock: CodecTypes['mongo/int32@1']['output'] | null;
      readonly description: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly username: CodecTypes['mongo/string@1']['output'];
      readonly password: CodecTypes['mongo/string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly EventSettings: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly date: CodecTypes['mongo/string@1']['input'];
      readonly location: CodecTypes['mongo/string@1']['input'];
    };
    readonly Order: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly buyerName: CodecTypes['mongo/string@1']['input'];
      readonly buyerPhone: CodecTypes['mongo/string@1']['input'];
      readonly buyerEmail: CodecTypes['mongo/string@1']['input'] | null;
      readonly items: ReadonlyArray<OrderItemInput>;
      readonly totalAmount: CodecTypes['mongo/int32@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Payment: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly orderId: CodecTypes['mongo/objectId@1']['input'];
      readonly method: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly waveReference: CodecTypes['mongo/string@1']['input'] | null;
      readonly confirmedByUserId: CodecTypes['mongo/objectId@1']['input'] | null;
      readonly confirmedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Ticket: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly orderId: CodecTypes['mongo/objectId@1']['input'];
      readonly ticketCategoryId: CodecTypes['mongo/objectId@1']['input'];
      readonly code: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly usedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly scannedByUserId: CodecTypes['mongo/objectId@1']['input'] | null;
    };
    readonly TicketCategory: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly price: CodecTypes['mongo/int32@1']['input'];
      readonly currency: CodecTypes['mongo/string@1']['input'];
      readonly stock: CodecTypes['mongo/int32@1']['input'] | null;
      readonly description: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly username: CodecTypes['mongo/string@1']['input'];
      readonly password: CodecTypes['mongo/string@1']['input'];
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly event_settings: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly date: { readonly bsonType: 'string' };
                    readonly location: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'date', 'location'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly orders: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly buyerName: { readonly bsonType: 'string' };
                    readonly buyerPhone: { readonly bsonType: 'string' };
                    readonly buyerEmail: { readonly bsonType: readonly ['null', 'string'] };
                    readonly items: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly ticketCategoryId: { readonly bsonType: 'objectId' };
                          readonly quantity: { readonly bsonType: 'int' };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly ['quantity', 'ticketCategoryId'];
                      };
                    };
                    readonly totalAmount: { readonly bsonType: 'int' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'buyerName',
                    'buyerPhone',
                    'createdAt',
                    'items',
                    'status',
                    'totalAmount',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly payments: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly orderId: { readonly bsonType: 'objectId' };
                    readonly method: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly waveReference: { readonly bsonType: readonly ['null', 'string'] };
                    readonly confirmedByUserId: {
                      readonly bsonType: readonly ['null', 'objectId'];
                    };
                    readonly confirmedAt: { readonly bsonType: readonly ['null', 'date'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'method', 'orderId', 'status'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly ticket_categories: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly price: { readonly bsonType: 'int' };
                    readonly currency: { readonly bsonType: 'string' };
                    readonly stock: { readonly bsonType: readonly ['null', 'int'] };
                    readonly description: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'currency', 'name', 'price'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly tickets: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'code'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly orderId: { readonly bsonType: 'objectId' };
                    readonly ticketCategoryId: { readonly bsonType: 'objectId' };
                    readonly code: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly usedAt: { readonly bsonType: readonly ['null', 'date'] };
                    readonly scannedByUserId: { readonly bsonType: readonly ['null', 'objectId'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'code',
                    'orderId',
                    'status',
                    'ticketCategoryId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly username: { readonly bsonType: 'string' };
                    readonly password: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'password', 'username'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly event_settings: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'EventSettings';
    };
    readonly ticket_categories: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'TicketCategory';
    };
    readonly orders: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Order' };
    readonly payments: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Payment';
    };
    readonly tickets: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Ticket' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly EventSettings: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'event_settings' };
          };
          readonly Order: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly buyerName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly buyerPhone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly buyerEmail: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly items: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'OrderItem' };
                readonly many: true;
              };
              readonly totalAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'orders' };
          };
          readonly Payment: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly method: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly waveReference: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly confirmedByUserId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly confirmedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly confirmedBy: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['confirmedByUserId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'payments' };
          };
          readonly Ticket: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly orderId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly ticketCategoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly usedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly scannedByUserId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
            };
            readonly relations: {
              readonly order: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Order';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['orderId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly ticketCategory: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'TicketCategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['ticketCategoryId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly scannedBy: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['scannedByUserId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'tickets' };
          };
          readonly TicketCategory: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly currency: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stock: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'ticket_categories' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly OrderItem: {
            readonly fields: {
              readonly ticketCategoryId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly OrderItem: {
      readonly fields: {
        readonly ticketCategoryId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly quantity: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
